version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      # Ajoutez d'autres variables d'environnement nécessaires ici, par exemple MongoDB URI
    volumes:
      - ./backend:/app/backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      # Ajoutez d'autres variables d'environnement nécessaires ici
    volumes:
      - ./frontend:/app/frontend

