version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    command: npm run dev
    environment:
      NODE_ENV: production
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

#  frontend:
#    build: frontend
#    ports:
#      - "80:80"
#    environment:
#      NODE_ENV: production
#      # Ajoutez d'autres variables d'environnement nécessaires ici
#    volumes:
#      - ./frontend:/app/frontend